spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/camelRoute?createDatabaseIfNotExist=true
    username: admin
    password: password
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

camelroutes:
  activemq:
    person-queue: test.queue